FROM docker.io/library/nginx:1.27-alpine
RUN mkdir -p /etc/nginx/auth /etc/nginx/certs
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY index.html /usr/share/nginx/html/index.html
COPY .htpasswd /etc/nginx/auth/.htpasswd

COPY certs/cert.pem /etc/nginx/certs/cert.pem
COPY certs/key.pem  /etc/nginx/certs/key.pem
EXPOSE 443
